### ISSUE TITLE
Read Ingest Sheets, has errors if there's additional text in the ingest form

### ISSUE THREAD

**Issue by dtcitron** [BershteynLab/EMODAnalyzeR#17]
Line 128 of - [R](https://github.com/BershteynLab/EMODAnalyzeR/tree/main/R)/ReadEMODResults.R

I am not able to get this to work, the read_excel function does not correctly parse the column names for the ingest form I am using for Malawi. The error (I think) is coming from there being additional notes off to the right which do not get parsed by EMOD but are interfering with read_excel.

I am not sure how to generalize this.

Can you point me to a path with an ingest file that works?

**Comment by kaftand** [comment]
Sure, on the dropbox:

Dropbox (NYU CEDS)\EMOD HIV User Group Shared Folder\input_file_bundles\Nyanza_calibration\k20220218_Nyanza_baseline_from_PrEP\Data 


Would you mind sharing your ingest file?

**Comment by dtcitron** [comment]
The ingest file which is throwing errors: Dropbox (NYU CEDS)/Malawi_EMOD_model_development/run_scenarios_Malawi/Data/calibration_ingest_form_Malawi_3_node_AB.xlsm

**Comment by kaftand** [comment]
Should be fixed in PR #19 , closing issue now
